lib: [
  "/home/eduardo/reason/reason-java-ffi/_esy/default/store/b/reason_java_ffi-30833ac1/install/default/lib/reason-java-ffi/META"
  "/home/eduardo/reason/reason-java-ffi/_esy/default/store/b/reason_java_ffi-30833ac1/install/default/lib/reason-java-ffi/dune-package"
  "/home/eduardo/reason/reason-java-ffi/_esy/default/store/b/reason_java_ffi-30833ac1/install/default/lib/reason-java-ffi/opam"
]
